build-job:
  stage: build
  script:
    - chmod -R 777 src/backend/src || true  # The || true prevents pipeline failure
    - echo "building docker containers" 
    - docker-compose build

test-backend:
  stage: test
  script:
    - docker-compose up 
    - docker-compose exec -T backend pytest -v || {
        echo "Tests failed"
        exit 1
      }
    - echo "All tests passed"
