services: 
  backend:
    build: src/backend/ 
    ports: 
      - "8000:8000"
    environment:
      - AWS_DEFAULT_REGION=us-west-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - ENDPOINT_URL=http://localstack:4566
    depends_on: 
      - localstack
    volumes:
      - ./src/backend:/app/
    develop:
      watch:
        - action: sync
          path: ./backend/
          target: /app/
        
  frontend:
    build: src/frontend/
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./src/frontend:/app/
    stdin_open: true
    tty: true
    command: /bin/bash
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME:-localstack-main}"
    image: localstack/localstack
    ports:
      - "4566:4566"            
    environment:
      - DEBUG=${DEBUG:-0}
      - DOCKER_HOST=unix:///var/run/docker.sock  # Add this line
      - LAMBDA_EXECUTOR=docker
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    privileged: true
  infrastructure: 
      build: src/infrastructure/    
      environment:
        - AWS_ACCESS_KEY_ID=test
        - AWS_SECRET_ACCESS_KEY=test
        - AWS_DEFAULT_REGION=us-west-1
        - CDK_DEFAULT_ACCOUNT=000000000000
        - CDK_DEFAULT_REGION=us-west-1
        - AWS_ENDPOINT_URL=http://localstack:4566
      volumes: 
        - ./src/:/app/
      depends_on: 
        - localstack
