AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sour Application

Resources:
  SourFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        SourApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY

Outputs:
  SourApi:
    Description: "API Gateway endpoint URL for Sour function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  SourFunction:
    Description: "Sour Lambda Function ARN"
    Value: !GetAtt SourFunction.Arn
