[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "PRISM"
version = "0.1.0"
description = "PRISM Services"
requires-python = ">=3.10"
authors = [
    { name = "Ricardo Baeza" }
]

[tool.hatch.build.targets.wheel]
packages = ["src"]
