"""Fixing Listing columns

Revision ID: 8a5d7920a8b6
Revises: 
Create Date: 2024-11-25 10:34:37.077096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5d7920a8b6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('seller_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'listings', 'users', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_column('listings', 'seller_id')
    # ### end Alembic commands ###
