/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CartScreen`; params?: Router.UnknownInputParams; } | { pathname: `/ChatsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/CheckoutScreen`; params?: Router.UnknownInputParams; } | { pathname: `/CompletedPurchaseScreen`; params?: Router.UnknownInputParams; } | { pathname: `/CreateListingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/CreatePostScreen`; params?: Router.UnknownInputParams; } | { pathname: `/DiscoverScreen`; params?: Router.UnknownInputParams; } | { pathname: `/LoggedOutScreen`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/MessagesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/SearchComponent`; params?: Router.UnknownInputParams; } | { pathname: `/SelfProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/SellerScreen`; params?: Router.UnknownInputParams; } | { pathname: `/SettingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/UserProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/VideosScreen`; params?: Router.UnknownInputParams; } | { pathname: `/createVideoScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/PostInfoScreen/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/CartScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/ChatsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/CheckoutScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/CompletedPurchaseScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/CreateListingScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/CreatePostScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/DiscoverScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/LoggedOutScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/MessagesScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/SearchComponent`; params?: Router.UnknownOutputParams; } | { pathname: `/SelfProfileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/SellerScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/SettingsScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/SignUpScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/UserProfileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/VideosScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/createVideoScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/PostInfoScreen/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/CartScreen${`?${string}` | `#${string}` | ''}` | `/ChatsScreen${`?${string}` | `#${string}` | ''}` | `/CheckoutScreen${`?${string}` | `#${string}` | ''}` | `/CompletedPurchaseScreen${`?${string}` | `#${string}` | ''}` | `/CreateListingScreen${`?${string}` | `#${string}` | ''}` | `/CreatePostScreen${`?${string}` | `#${string}` | ''}` | `/DiscoverScreen${`?${string}` | `#${string}` | ''}` | `/LoggedOutScreen${`?${string}` | `#${string}` | ''}` | `/LoginScreen${`?${string}` | `#${string}` | ''}` | `/MessagesScreen${`?${string}` | `#${string}` | ''}` | `/SearchComponent${`?${string}` | `#${string}` | ''}` | `/SelfProfileScreen${`?${string}` | `#${string}` | ''}` | `/SellerScreen${`?${string}` | `#${string}` | ''}` | `/SettingsScreen${`?${string}` | `#${string}` | ''}` | `/SignUpScreen${`?${string}` | `#${string}` | ''}` | `/UserProfileScreen${`?${string}` | `#${string}` | ''}` | `/VideosScreen${`?${string}` | `#${string}` | ''}` | `/createVideoScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CartScreen`; params?: Router.UnknownInputParams; } | { pathname: `/ChatsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/CheckoutScreen`; params?: Router.UnknownInputParams; } | { pathname: `/CompletedPurchaseScreen`; params?: Router.UnknownInputParams; } | { pathname: `/CreateListingScreen`; params?: Router.UnknownInputParams; } | { pathname: `/CreatePostScreen`; params?: Router.UnknownInputParams; } | { pathname: `/DiscoverScreen`; params?: Router.UnknownInputParams; } | { pathname: `/LoggedOutScreen`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/MessagesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/SearchComponent`; params?: Router.UnknownInputParams; } | { pathname: `/SelfProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/SellerScreen`; params?: Router.UnknownInputParams; } | { pathname: `/SettingsScreen`; params?: Router.UnknownInputParams; } | { pathname: `/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/UserProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/VideosScreen`; params?: Router.UnknownInputParams; } | { pathname: `/createVideoScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/+not-found` | `/PostInfoScreen/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/PostInfoScreen/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
