/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/DiscoverScreen`; params?: Router.UnknownInputParams; } | { pathname: `/ListingInfoScreen`; params?: Router.UnknownInputParams; } | { pathname: `/LoggedOutScreen`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/MessagesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/SellerScreen`; params?: Router.UnknownInputParams; } | { pathname: `/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/VideosScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | ``; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/DiscoverScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/ListingInfoScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/LoggedOutScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/MessagesScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/ProfileScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/SellerScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/SignUpScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/VideosScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | ``; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/DiscoverScreen${`?${string}` | `#${string}` | ''}` | `/ListingInfoScreen${`?${string}` | `#${string}` | ''}` | `/LoggedOutScreen${`?${string}` | `#${string}` | ''}` | `/LoginScreen${`?${string}` | `#${string}` | ''}` | `/MessagesScreen${`?${string}` | `#${string}` | ''}` | `/ProfileScreen${`?${string}` | `#${string}` | ''}` | `/SellerScreen${`?${string}` | `#${string}` | ''}` | `/SignUpScreen${`?${string}` | `#${string}` | ''}` | `/VideosScreen${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/DiscoverScreen`; params?: Router.UnknownInputParams; } | { pathname: `/ListingInfoScreen`; params?: Router.UnknownInputParams; } | { pathname: `/LoggedOutScreen`; params?: Router.UnknownInputParams; } | { pathname: `/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/MessagesScreen`; params?: Router.UnknownInputParams; } | { pathname: `/ProfileScreen`; params?: Router.UnknownInputParams; } | { pathname: `/SellerScreen`; params?: Router.UnknownInputParams; } | { pathname: `/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/VideosScreen`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | ``; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
